specVersion: 0.2.0
name: subquery-query-registry-project
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b' # Moonriver
  endpoint: wss://moonriver.api.onfinality.io/public-ws

  chaintypes:
    file: "./types.yaml"
dataSources:
  - kind: substrate/Moonbeam
    startBlock: 1
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
    abi: queryRegistry
    assets:
      queryRegistry:
        file: ./queryRegistry.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleNewQuery
          kind: substrate/MoonbeamEvent
          filter:
            address: '0x0000000000' #TODO
            topics:
              - CreateQuery(uint256 queryId, address creator, bytes32 metadata)
        - handler: handleUpdateQuery
          kind: substrate/MoonbeamCall
          filter:
            to: '0x0000000000' #TODO
            function: updateQueryProject(uint256 queryId, bytes32 version, bytes32 deploymentId, bytes32 metadata)
        - handler: handleStartIndexing
          kind: substrate/MoonbeamEvent
          filter:
            address: '0x0000000000' #TODO
            topics:
              - StartIndexing(address indexer, bytes32 deploymentId)
        - handler: handleIndexingUpdate
          kind: substrate/MoonbeamEvent
          filter:
            address: '0x0000000000' #TODO
            topics:
              - UpdateDeploymentStatus(address indexer, bytes32 deploymentId, uint256 blockheight, bytes32 mmrRoot, uint256 timestamp, IndexingServiceStatus status)
        - handler: handleStopIndexing
          kind: substrate/MoonbeamEvent
          filter:
            address: '0x0000000000' #TODO
            topics:
              - StopIndexing(address indexer, bytes32 deploymentId)
