specVersion: 0.2.0
name: subquery-query-registry-project
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x956876d5b80e47e523a6629b3c3ac3e42f2850ad12e236d87a0aaac87c9f6bc9' # Moonriver
  endpoint: ws://127.0.0.1:9944

  chaintypes:
    file: "./types.yaml"
dataSources:
  - kind: substrate/Moonbeam
    startBlock: 1
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
      options:
        abi: queryRegistry
        address: '0xeAB4eEBa1FF8504c124D031F6844AD98d07C318f'
    assets:
      queryRegistry:
        file: ./src/queryRegistry.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleNewQuery
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - CreateQuery(uint256 queryId, address creator, bytes32 metadata, bytes32 deploymentId, bytes32 version)
        - handler: handleUpdateQueryMetadata
          kind: substrate/MoonbeamEvent
          filter:
            topics: UpdateQueryMetadata(address owner, uint256 queryId, bytes32 metadata)
        - handler: handleUpdateQueryDeployment
          kind: substrate/MoonbeamEvent
          filter:
            topics: UpdateQueryDeployment( address owner, uint256 queryId, bytes32 deploymentId, bytes32 version)
        - handler: handleStartIndexing
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - StartIndexing(address indexer, bytes32 deploymentId)
        - handler: handleIndexingUpdate
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - UpdateDeploymentStatus(address indexer, bytes32 deploymentId, uint256 blockheight, bytes32 mmrRoot, uint256 timestamp, IndexingServiceStatus status)
        - handler: handleStopIndexing
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - StopIndexing(address indexer, bytes32 deploymentId)
