specVersion: 0.2.0
name: subquery-query-registry-project
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  # genesisHash: '0x956876d5b80e47e523a6629b3c3ac3e42f2850ad12e236d87a0aaac87c9f6bc9' # Moonriver
  genesisHash: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527' # Moonbase Alpha
  endpoint: wss://moonbeam-alpha.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/moonbase-alpha-dictionary

  chaintypes:
    file: ./chaintypes.js


x-moonbeam: &moonbeam
  kind: substrate/Moonbeam
  startBlock: 1545235 #TODO
  processor: &moonbeam-processor
    file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
  assets:
    eraManager:
      file: ./node_modules/@subql/contract-sdk/publish/contracts/EraManager.json
    staking:
      file: ./node_modules/@subql/contract-sdk/publish/contracts/Staking.json
    indexerRegistry:
      file: ./node_modules/@subql/contract-sdk/publish/contracts/IndexerRegistry.json
    queryRegistry:
      file: ./node_modules/@subql/contract-sdk/publish/contracts/QueryRegistry.json

dataSources:
  - <<: *moonbeam
    processor:
      <<: *moonbeam-processor
      options:
        abi: eraManager
        # TODO
        # address: '0x'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleNewEra
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - NewEraStart(uint256 indexed era, address caller)
  - <<: *moonbeam
    processor:
      <<: *moonbeam-processor
      options:
        abi: indexerRegistry
        # TODO
        # address: '0x'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleRegisterIndexer
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - RegisterIndexer(address indexed indexer, uint256 amount, bytes32 metadata)
        - handler: handleUnregisterIndexer
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - UnregisterIndexer(address indexed indexer);
        - handler: handleUpdateIndexerMetadata
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - UpdateMetadata(address indexed indexer, bytes32 metadata)
        - handler: handleSetControllerAccount
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - SetControllerAccount(address indexed indexer, address indexed controller)
        - handler: handleRemoveControllerAccount
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - RemoveControllerAccount(address indexed indexer, address indexed controller)
        - handler: handleSetCommissionRate
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - SetCommissionRate(address indexed indexer, uint256 amount)
  - <<: *moonbeam
    processor:
      <<: *moonbeam-processor
      options:
        abi: staking
        # TODO
        # address: '0x'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleAddDelegation
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - DelegationAdded(address indexed source, address indexed indexer, uint256 amount)
        - handler: handleRemoveDelegation
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - DelegationRemoved(address indexed source, address indexed indexer, uint256 amount)
        - handler: handleWithdrawRequested
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - UnbondRequested(address indexed source, address indexed indexer, uint256 amount)
        - handler: handleWithdrawClaimed
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - UnbondWithdrawn(address indexed source, address indexed indexer, uint256 amount, uint256 burnAmount)
  - <<: *moonbeam
    processor:
      <<: *moonbeam-processor
      options:
        abi: queryRegistry
        # TODO
        # address: '0x'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleNewQuery
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - CreateQuery(uint256 queryId, address creator, bytes32 metadata, bytes32 deploymentId, bytes32 version)
        - handler: handleUpdateQueryMetadata
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - UpdateQueryMetadata(address owner, uint256 queryId, bytes32 metadata)
        - handler: handleUpdateQueryDeployment
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - UpdateQueryDeployment(address owner, uint256 queryId, bytes32 deploymentId, bytes32 version)
        - handler: handleStartIndexing
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - StartIndexing(address indexer, bytes32 deploymentId)
        - handler: handleIndexingUpdate
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - UpdateDeploymentStatus(address indexer, bytes32 deploymentId, uint256 blockheight, bytes32 mmrRoot, uint256 timestamp)
        - handler: handleIndexingReady
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - UpdateIndexingStatusToReady(address indexer, bytes32 deploymentId)
        - handler: handleStopIndexing
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - StopIndexing(address indexer, bytes32 deploymentId)
