specVersion: 0.2.0
name: subquery-query-registry-project
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  # SQN testnet
  genesisHash: '0x6b18138563ba86208d17839ff4f48e2f1fcaddb520de82bb6a731bcb5e801e85'
  # endpoint: 'https://node-6901336963938430976.jm.onfinality.io/rpc?apikey=65f0a4da-7861-429b-a21d-fd42209f4d2f'
  endpoint: 'wss://sqtn.api.onfinality.io/public-ws'

  chaintypes:
    file: ./dist/chaintypes.js

x-frontier: &frontier
  kind: substrate/FrontierEvm
  startBlock: 20586
  processor: &frontier-processor
    file: './dist/frontierEvm.js'
  assets:
    eraManager:
      file: ./node_modules/@subql/contract-sdk/publish/contracts/EraManager.json
    staking:
      file: ./node_modules/@subql/contract-sdk/publish/contracts/Staking.json
    indexerRegistry:
      file: ./node_modules/@subql/contract-sdk/publish/contracts/IndexerRegistry.json
    queryRegistry:
      file: ./node_modules/@subql/contract-sdk/publish/contracts/QueryRegistry.json
    planManager:
      file: ./node_modules/@subql/contract-sdk/publish/contracts/PlanManager.json
    serviceAgreementRegistry:
      file: ./node_modules/@subql/contract-sdk/publish/contracts/ServiceAgreementRegistry.json
    rewardsDistributor:
      file: ./node_modules/@subql/contract-sdk/publish/contracts/RewardsDistributer.json

dataSources:
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: eraManager
        address: '0x48Fb7775f08909CaE6BD8C8B1dDdCD11Df35f70a'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleNewEra
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - NewEraStart(uint256 indexed era, address caller)
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: indexerRegistry
        address: '0xBfF73BfeB2Ab4335610fA4757F0Fc35862A23f6F'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleRegisterIndexer
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - RegisterIndexer(address indexed indexer, uint256 amount, bytes32 metadata)
        - handler: handleUpdateIndexerMetadata
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - UpdateMetadata(address indexed indexer, bytes32 metadata)
        - handler: handleSetControllerAccount
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - SetControllerAccount(address indexed indexer, address indexed controller)
        - handler: handleRemoveControllerAccount
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - RemoveControllerAccount(address indexed indexer, address indexed controller)
        - handler: handleUnregisterIndexer
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - UnregisterIndexer(address indexed indexer)
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: staking
        address: '0x9f84F585CD0A1F234824b4507e4497a9a7d11669'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleAddDelegation
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - DelegationAdded(address indexed source, address indexed indexer, uint256 amount)
        - handler: handleRemoveDelegation
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - DelegationRemoved(address indexed source, address indexed indexer, uint256 amount)
        - handler: handleWithdrawRequested
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - UnbondRequested(address indexed source, address indexed indexer, uint256 amount, uint256 index)
        - handler: handleWithdrawClaimed
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - UnbondWithdrawn(address indexed source, uint256 amount, uint256 index)
        - handler: handleSetCommissionRate
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - SetCommissionRate(address indexed indexer, uint256 amount)
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: queryRegistry
        address: '0x1bE2367239E965B281ed1D182B6e9b89BF2133A7'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleNewQuery
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - CreateQuery(uint256 queryId, address creator, bytes32 metadata, bytes32 deploymentId, bytes32 version)
        - handler: handleUpdateQueryMetadata
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - UpdateQueryMetadata(address owner, uint256 queryId, bytes32 metadata)
        - handler: handleUpdateQueryDeployment
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - UpdateQueryDeployment(address owner, uint256 queryId, bytes32 deploymentId, bytes32 version)
        - handler: handleStartIndexing
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - StartIndexing(address indexer, bytes32 deploymentId)
        - handler: handleIndexingUpdate
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - UpdateDeploymentStatus(address indexer, bytes32 deploymentId, uint256 blockheight, bytes32 mmrRoot, uint256 timestamp)
        - handler: handleIndexingReady
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - UpdateIndexingStatusToReady(address indexer, bytes32 deploymentId)
        - handler: handleStopIndexing
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - StopIndexing(address indexer, bytes32 deploymentId)
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: planManager
        address: '0xa3205536Bb0040f7a607E8C0480319596C5df5Cc'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handlePlanTemplateCreated
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - PlanTemplateCreated(uint256 indexed planTemplateId)
        - handler: handlePlanTemplateMetadataUpdated
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - PlanTemplateMetadataChanged(uint256 indexed planTemplateId, bytes32 metadata)
        - handler: handlePlanTemplateStatusUpdated
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - PlanTemplateStatusChanged(uint256 indexed planTemplateId, bool active)
        - handler: handlePlanCreated
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - PlanCreated(address indexed creator, bytes32 indexed deploymentId, uint256 planTemplateId, uint256 planId, uint256 price)
        - handler: handlePlanRemoved
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - PlanRemoved(address indexed source, uint256 id, bytes32 deploymentId)
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: serviceAgreementRegistry
        address: '0x4B4fE7232D53eaBE8970AF5678648E3B65F6E302'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleServiceAgreementCreated
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - ServiceAgreementCreated(address indexed consumer, address indexed indexer, bytes32 indexed deploymentId, address serviceAgreement)
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: rewardsDistributor
        address: '0x409016c8b787f5bf98Dc68C7e9c542509e3F9c27'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleRewardsDistributed
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - DistributeRewards(address indexed indexer, uint256 indexed eraIdx)
        - handler: handleRewardsClaimed
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - ClaimRewards(address indexed indexer, address indexed delegator, uint256 rewards)
        - handler: handleRewardsUpdated
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - RewardsChanged(address indexed indexer, uint256 indexed eraIdx, uint256 additions, uint256 removals)
